name: Deploying to Azure Blob Storage

on:
  push:
    branches:
      - main
      
env:
  AZURE_STORAGE_ACCOUNT: <storageacc1998app>
  AZURE_STORAGE_ACCESS_KEY: <I7aWS/jbOGkNTLCJKxBteqmCoanoP2JVCmQ3KqtcuZxwN3azfM+ccbco6fXut3YosO+zuH5S5ZQZ+ASti2wcXA==>
  CONTAINER_NAME: <$web>
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: start application
      run: npm run build
      
    - name: Upload files to Azure Blob Storage
      uses: azure/CLI@v1
      with:
          inlineScript: |
            az storage blob upload-batch \
            --destination '$web' \
            --account-name storageacc1998app \
            --account-key I7aWS/jbOGkNTLCJKxBteqmCoanoP2JVCmQ3KqtcuZxwN3azfM+ccbco6fXut3YosO+zuH5S5ZQZ+ASti2wcXA== \
            --source ./build
